import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.css"
import "../styles/bootstrap/css/bootstrap-grid.css";

const inter = Inter({subsets: ["latin"]})
import styles from "../styles/main.module.scss";
import {Providers} from "@/app/utils/providers"


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({children}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
		<body className={`${inter.className} ${styles.styleguide}`}>
		<Providers>
			{children}
		</Providers>
		</body>
		</html>
	)
}
